services:
  # Nome do nosso serviço
  erp-app:
    # Constrói a imagem a partir do Dockerfile no diretório atual (.)
    build: .
    # Nome da imagem que será criada
    image: meu-erp-local
    # Mapeamento de portas: <porta_na_sua_maquina>:<porta_no_container>
    ports:
      - "8080:8080"
    # AQUI ESTÁ A MÁGICA DOS VOLUMES:
    volumes:
      # Mapeia a pasta './dados' (na sua máquina) para a pasta '/app/data' (no container)
      - ./dados:/app/data
    # Garante que o container reinicie se houver alguma falha
    restart: unless-stopped